models:
  - name: dim_movies
    description: Dimension table for cleansed movie metadata
    columns:
      - name: movie_id
        description: Unique identifier for each movie.
        tests: 
          - not_null 
      - name: movie_title 
        description: Standardized movie movie_title
        tests: 
          - not_null
      - name: genre_array 
        description: List of genres in array format
      - name: genres 
        description: Raw genre string from sources 

  - name: dim_users
    description: Dimension table for unique users from both ratings 
    columns:
      - name: user_id
        description: unique user identifiers  
        tests: 
          - unique
          - not_null 
    
  - name: dim_genome_tags
    description: Dimension table of genome tag labels 
    columns: 
      - name: tag_id
        description: unique tag ID
        tests: 
          - not_null
          # Unique

  - name: fct_ratings
    description: fact table of user rarings for movies 
    columns:
      - name: user_id 
        description: Foreign key to dim_users
        tests: 
          - not_null
      - name: movie_id
        description: Foreign keys to dim_movies
        tests: 
            - not_null
            - relationships:
                arguments:
                  to: ref('dim_movies')
                  field: movie_id 
      - name: rating 
        description: Rating provided by a user for a movie.
        tests: 
            - not_null
      - name: rating_timestamp 
        description: Timestamp indicating when the rating was submitted.
  - name: fct_genome_scores
    description: Fact table of relevance scores per movies and tag 
    columns: 
      - name: movie_id
        description: Foreign key to dim_movies 
        tests:
            - not_null
      - name: tag_id 
        description: Foreign key to dim_genome_tags
        tests: 
          - not_null
      - name: relevance_score
        description: relevance score (0 to 1) for tag's association with 